FROM openjdk:17-jdk-slim

WORKDIR /app

COPY target/blob-storage-1.0-jar-with-dependencies.jar /app/blob-storage-1.0-jar-with-dependencies.jar

CMD ["java", "-jar", "blob-storage-1.0-jar-with-dependencies.jar"]