services:
  tukano-app:
    build:
      context: ./tukano
    depends_on:
      - redis
      - postgres
      - storage
    image: tukano-app
    container_name: tukano-app
    environment:
      - EXTERNAL_HOST=localhost
      - EXTERNAL_PORT=8080
      - CACHE_TYPE=REDIS
      - REDIS_KEY=${REDIS_KEY}
      - HIBERNATE_CONFIG=postgres.cfg.xml
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - BLOB_STORAGE_TYPE=REMOTE
      - BLOB_STORAGE_TOKEN=${BLOB_STORAGE_TOKEN}
      - USE_AUTH=FALSE
    ports:
      - "8080:8080"

  storage:
    build:
      context: ./blob-storage
    image: storage
    container_name: storage
    environment:
      - STORAGE_TOKEN=${BLOB_STORAGE_TOKEN}

  redis:
    image: redis
    container_name: redis
    command: ["redis-server", "--requirepass", "${REDIS_KEY}"]

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}