apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgres
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: tukano-secrets
                  key: DB_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tukano-secrets
                  key: DB_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: tukano-secrets
                  key: DB_NAME
                  
          image: postgres
          name: postgres
          
      restartPolicy: Always
